languageCode = "ja-JP"
baseURL = ""
title = "Firefox学生マーケティングチーム"
theme = "anubis"
paginate = 10
disqusShortname = "fxstudent"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
